version: '3.3'
services:
  # NGINX webservers with nginx-demo hello page
  nginx1:
      hostname: nginx1
      build: nginx-hello
      expose:
        - "80"
  nginx2:
      hostname: nginx2
      build: nginx-hello
      ports:
        - "80"
  # Defining a third server with name nginx3
  nginx3:
      hostname: nginx3
      build: nginx-hello
      ports:
        - "80"

  # NGINX Plus Load Balancer
  nginx-plus:
      hostname: nginx-plus
      build: 
         context: nginx-plus
         dockerfile: Dockerfile_ubuntu
      volumes:
          - ./nginx-plus/etc/nginx:/etc/nginx
      ports:
          - 8080:8080
          - 80:80
          - 443:443
      restart: always

  prometheus:
      hostname: prometheus
      image: nginx/nginx-prometheus-exporter:0.11
      command: 
          - -nginx.plus
          - -nginx.scrape-uri=http://nginx-plus:8080/api
      ports:
          - 9113:9113
      restart: always
