
# For CentOS 7:
FROM centos:centos7

LABEL maintainer="sh.dutta@f5.com"

# Download certificate and key from the customer portal (https://cs.nginx.com)
# and copy to the build context:
COPY etc/ssl/nginx/nginx-repo.* /etc/ssl/nginx/
RUN chmod 644 /etc/ssl/nginx/* 

# Install prerequisite packages:
RUN yum -y install wget ca-certificates epel-release

# Add NGINX Plus repo to Yum:
RUN wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/nginx-plus-7.4.repo

# Install NGINX Plus:
RUN yum -y install nginx-plus \
    && yum clean all \
    && rm -rf /var/cache/yum

# Copy certificate files and dhparams
COPY etc/ssl /etc/ssl

# COPY /etc/nginx (Nginx configuration) directory:
COPY etc/nginx /etc/nginx

# Forward request logs to Docker log collector:
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# Remove the Nginx Plus cert/keys from the image:
RUN rm /etc/ssl/nginx/nginx-repo.crt /etc/ssl/nginx/nginx-repo.key

# EXPOSE ports, HTTP 80, HTTPS 443 and, Nginx status page 8080
EXPOSE 80 443 8080
STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]